name: Git Workshop Demo

on:
    push:
        branches:
            - 'feature/**'
            - 'bugfix/**'
            - 'chore/**'

env:
    SERVER_IP: '127.0.0.1'
    COMPANY_NAME: "NTPLC"
    REPO_NAME: ${{ github.repository }}
jobs:
    job-1:
        runs-on: ubuntu-latest
        env:
            PHONE: '123-456-7890'
        steps:
            - run: echo "${{ github.actor }}"
            - run: echo "Hello ${{ env.COMPANY_NAME }}"
            - run: echo "${{ env.REPO_NAME }}"
            - run: echo "Contact us at ${{ env.PHONE }}"
            - run: echo "${{ vars.APP_NAME }}"
            - run: echo "${{ secrets.API_KEY }}"
    job-2:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello ${{ env.COMPANY_NAME }}"
            - run: echo "Server IP is ${{ env.SERVER_IP }}"